EXERCISE 1

In [20]:
import numpy as np 

tab = np.random.randint(0,9,10)
tab

array([0, 3, 5, 0, 1, 7, 7, 0, 5, 2], dtype=int32)

EXERCISE 2


In [22]:
li = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
li

array([3, 2, 0, 1, 2])

EXERCISE 3

In [23]:
tab2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

tab2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

EXERCISE 4

In [26]:
tab3 = np.array([[0.56, 0.85, 0.01, 0.42, 0.68],
                  [0.22, 0.37, 0.73, 0.93, 0.39],
                  [0.44, 0.03, 0.87, 0.02, 0.83],
                  [0.78, 0.87, 0.98, 0.80, 0.46]])

tab3

array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.8 , 0.46]])

EXERCISE 5

In [30]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

array[1:,][1]

array([21, 22, 23, 22, 22])

EXERCISE 6

In [33]:
array= np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])



AttributeError: 'numpy.ndarray' object has no attribute 'invert'